### ISSUE TITLE
Cannot get RestComm docker image to work in OSX

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Docker#10]
Followed the docker guide for OSX at https://docs.docker.com/v1.8/installation/mac/

Docker installation went smoothly and docker 'hello-world' worked fine. Then I installed mobicents/restcomm:latest from docker hub and tried to bring it up with the command found in this repo for secure installation:

```
$ docker run -e SECURE="true" -e SSL_MODE="allowall" -e USE_STANDARD_PORTS="true" -e VOICERSS_KEY="<key>" --name=restcomm -d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65535:65000-65535/udp mobicents/restcomm:latest
```

First issue I got is: 

```
'Error response from daemon: Cannot start container 11079caa823ccf5af6e96bd006a7d05693128daa819a7d6e6df5cefc72643d19: failed to create endpoint restcomm on network bridge: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 0/0 --dport 65118 -j DNAT --to-destination 172.17.0.2:65118 ! -i docker0:  (fork/exec /usr/local/sbin/iptables: cannot allocate memory)'
```

Which seemed like an issue with the port mapping for port '65118' (which by the way I checked and netstat doesn't show as used in OSX). Anyway I tried removing that port from the command (just to get over this issue and see if the installation works with that aside) and indeed it worked:

```
$ docker run -e SECURE="true" -e SSL_MODE="allowall" -e USE_STANDARD_PORTS="true" -e VOICERSS_KEY="<key>" --name=restcomm -d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65117:65000-65117/udp mobicents/restcomm:latest
```

The second issue I see is that afterwards when I use docker exec to open a shell inside the container no java processes are running there. Notice that:
- in RESTCOMM/standalone/configuration the restcomm.keystore file is there, so no problem here.
- there is no RESTCOMM/standalone/log directory so I can't see what is going on, but seems that there was an issue before RestComm started to come up

Any ideas?

Thanks

**Comment by atsakiridis** [comment]
After some more troubleshooting, seems that restcomm-start/stop.sh scripts are not executable for some reason. So when I manually make them executable and run restcomm-start.sh RestComm seems to come up without issues, but the problem is that when starting with restcomm-start.sh, the port mapping used in the docker run command line isn't respected and instead ports 5080-5083 are used for sip signaling instead of 5060-5063. As a result docker is forwarding the traffic to the wrong ports and it doesn't work

I also tried @gvagenas  suggestion on running with sudo (after fixing the environment for sudo for it to work in the docker OSX environment) and still getting issues. Maybe sudo doesn't change a lot because in OSX docker command resides in the OSX host, while the docker daemon is on the virtual box vm machine.

**Comment by atsakiridis** [comment]
I finally managed to make RestComm docker image work on OSX but using a different approach. Instead of following the official guide (with which I had the issues described above), I just used a new Virtual Box VM where I installed an Ubuntu Server image and then installed docker, etc. Please check:

https://github.com/Mobicents/Restcomm-Docker/blob/master/README.md#running-restcomm-docker-image-in-osx-host

**Comment by leftyb** [comment]
@atsakiridis  can we close this issue?

**Comment by hrosa** [comment]
@leftyb @atsakiridis I managed to have restcomm docker working on OSX.
Followed this article for docker installation: https://docs.docker.com/engine/installation/mac/

We do need to update the docker quick starting guide for OSX, because there are some caveats. Docker architecture is slightly different between Linux and OSX.

**Comment by atsakiridis** [comment]
Great. If @hrosa found a way to make it work with the official procedure (i.e. https://docs.docker.com/engine/installation/mac/) then we can close this. But @hrosa please update the documentation. The current documentation I think was using manually installing virtual box and installing docker inside a linux guest because that was how I managed to get it to work for me. But yeah we should prefer the official way @leftyb

**Comment by hrosa** [comment]
Already opened issue #44 

Will provide guidelines when possible.

**Comment by achikin** [comment]
Any updates on this? It seems like restcomm binds to docker-machine nat ip address(eth0 10.0.2.15 for me) instead of bridge(eth1 192.168.99.100)

**Comment by deruelle** [comment]
@hrosa will provide a better set of instructions

**Comment by achikin** [comment]
I've figured out a working configuration by myself
Mention that you should set up your own `VOICERSS_KEY`

```
docker run -e MEDIASERVER_LOWEST_PORT="65000" \ 
-e MEDIASERVER_HIGHEST_PORT="65050" \
-e VOICERSS_KEY="<YOUR-VOICERSS-KEY>" \
-e STATIC_ADDRESS=$(docker-machine ip) \
-e USE_STANDARD_PORTS="true" \
--name=restcomm \
-d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 \
-p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp \
-p 65000-65050:65000-65050/udp \
restcomm/restcomm:latest
```

But I still have several questions:
1) Why doesn't it work without USE_STANDARD_PORTS="true". If you remove that - Jitsi does not connect and admin console is not reachable. What does USE_STANDARD_PORTS do?
2) If I try to set `--net=host` restcomm binds to my `eth0` interface instead of my `docker0` interface. Nothing works in such configuration. How can I fix that?

**Comment by deruelle** [comment]
1) @achikin see http://docs.telestax.com/restcomm-docker-important-ports/ for ports and USE_STANDARD_PORTS description.

2) it should work. What doesn't work exactly ? @leftyb can help out here

**Comment by leftyb** [comment]
Hi @achikin,

Please consult Docker documentation on --net flag : https://docs.docker.com/engine/userguide/networking/dockernetworks/

Using --net host, you actually  are using hosts network stack. That is why container is not using docker0 which is the default bridge network created/used by Docker. Can you please provide information on what problems you face using --net host?

**Comment by achikin** [comment]
@leftyb 

```
→ docker run -e MEDIASERVER_LOWEST_PORT="65000" -e MEDIASERVER_HIGHEST_PORT="65050" -e VOICERSS_KEY="[deleted]" -e STATIC_ADDRESS=$(docker-machine ip) -e USE_STANDARD_PORTS="true" --name=restcomm -d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65050:65000-65050/udp restcomm/restcomm:latest
7bf1f4b9caf19e264f29bdf24201f1234b32e15fab27c15812298ce3f55c7519
→ curl $(docker-machine ip)
<!DOCTYPE html>
<html ng-app="rcApp">
    <head>
        <title>RestComm</title>
```

As expected: restcomm containter responds on docker-machine's ip.
Now let's add --net=host

```
→ docker run -e MEDIASERVER_LOWEST_PORT="65000" -e MEDIASERVER_HIGHEST_PORT="65050" -e VOICERSS_KEY="[deleted]" -e STATIC_ADDRESS=$(docker-machine ip) -e USE_STANDARD_PORTS="true" --name=restcomm -d -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65050:65000-65050/udp --net=host restcomm/restcomm:latest
a7c8a6740a5e0f4265dd137ed2e5dd06de1df5757bb296217d6801ba9331962d
→ curl $(docker-machine ip)
curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused
^^^^something wrong
→ docker-machine ssh
docker@default:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:9F:9F:2D:4F  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
eth0      Link encap:Ethernet  HWaddr 08:00:27:3A:E4:B2  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
eth1      Link encap:Ethernet  HWaddr 08:00:27:90:2A:73  
          inet addr:192.168.99.100  Bcast:192.168.99.255  Mask:255.255.255.0
docker@default:~$ curl 10.0.2.15
<!DOCTYPE html>
<html ng-app="rcApp">
    <head>
        <title>RestComm</title>
```

E.g. restcomm responds on eth0, but should respond on eth1 which is $(docker-machine ip) - the only interface visible from outside of the host.

**Comment by leftyb** [comment]
Hi,
RestComm is using eth0 by default. At the next release we added an option to be able to define the interface that you want to use. For the moment you need to use eth0. This week we are planning to add this option at the restcomm/restcomm:master tag, but as explained [here](http://docs.telestax.com/restcomm-docker-quick-start-guide/) will not include a stable RestComm release but the development pre-release version. 

best regards.

**Comment by achikin** [comment]
Thank you for explanations!

**Comment by maria-farooq** [comment]
@deruelle  @hrosa  as we have separate issue for documentation https://github.com/RestComm/Restcomm-Docker/issues/44 , i think we can close this one. or we can close either one of these, however it is ok.

**Comment by agafox** [comment]
@deruelle let's close this issue because it's not actual
