### ISSUE TITLE
Container cannot start on OSX 10.12.3

### ISSUE THREAD

**Issue by wpcfan** [RestComm/Restcomm-Docker#100]
I do what 'Get Started' told us, and cannot get docker running. 

Always got the following error:

```
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 353, in <module>
    main(args)
  File "/sbin/my_init", line 272, in main
    export_envvars()
  File "/sbin/my_init", line 88, in export_envvars
    f.write(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)
```

**Comment by gsaslis** [comment]
@wpcfan could you please share some more feedback about this?

what command did you run to get this output and what was the complete error log?

**Comment by agafox** [comment]
@wpcfan @gsaslis '/sbin/my_init' is a script from original ubuntu container and it's not modified by Restcomm-Docker. It seems that issue was fixed https://github.com/phusion/baseimage-docker/issues/96
