### ISSUE TITLE
Restcomm Docker image not working on OSX 10.12.3

### ISSUE THREAD

**Issue by bpulito** [RestComm/Restcomm-Docker#101]
I realize there is already an issue open for running the Restcomm Docker image on Docker for Mac but my symptoms look a bit different. When I try to make a call to +1234 from Olypmus after Registering Alice the call fails and I get the following error:

18:37:14,547 ERROR [org.restcomm.connect.mgcp.Link] (RestComm-akka.actor.default-dispatcher-25) The media gateway failed to respond in the requested timout period.

It looks like the media server is binding with no errors so not clear on why this is not working. I followed these instructions for setting this up:

http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.html#restcomm-docker/

I'm attaching my logs files as well.
[logs.zip](https://github.com/RestComm/Restcomm-Docker/files/768822/logs.zip)

**Comment by deruelle** [comment]
@bpulito can you try with --net=host instead of port forwarding. It's weird the RMS is bound to the right IP and Port and we see from the network trace that the MGCP is sent to the right IP and port but it looks like it never reaches the RMS, so sounds like a networking issue. or you can also try to add -p 2427:2427 -p 2727:2727 ?

**Comment by bpulito** [comment]
I tried both of these suggestions and neither resolved the issue. When I exec into the restcomm docker container it looks like the media server is not listening on 2427. Here is the netstat:

root@4f90566914ac:/# netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 172.17.0.2:443          0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:4447         0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:5060         0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:5061         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9990          0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:5062         0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:5063         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:80           0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.2:5063         172.17.0.1:60444        ESTABLISHED
udp        0      0 172.17.0.2:2727         0.0.0.0:*
udp        0      0 172.17.0.2:5060         0.0.0.0:*

The media server log shows that the channel is binding with no errors:

2017-02-11 21:16:17,301 INFO  [MgcpProvider] (main) Binding channel to 172.17.0.2:2427

**Comment by leftyb** [comment]
Hi @bpulito 

RestComm-Docker container philosophy has changed, after RMS5 integration. Please pull latest tag again and run command like so: 
`
docker run -i -t --name=restcomm-myInstance -v /var/log/restcomm/:/var/log/restcomm/ -e RCBCONF_STATIC_ADDRESS="my eth0 ip" -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/master/env_files/restcomm_env_locally.sh" -p 80:80 -p 443:443 -p 9990:9990 -p 5080:5080 -p 5081:5081 -p 5082:5082 -p 5083:5083 -p 5080:5080/udp -p 65000-65050:65000-65050/udp restcomm/restcomm:latest `

As suggested above It is recommended to use "--net host" at your RUN command. This way docker container is added on the hosts network stack. So the RUN command can be like: 
`docker run -i -t  --net host -v /var/log/restcomm/:/var/log/restcomm/ -e RCBCONF_STATIC_ADDRESS="my eth0 ip" -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/master/env_files/restcomm_env_locally.sh"  --name=restcomm-myInstance   restcomm/restcomm:latest `

**Comment by phucnguyen2411** [comment]
@leftyb : Thanks so much, it working well on my system.

**Comment by gsaslis** [comment]
@bpulito i'm trying to help clean up here... 

would you mind trying out to confirm if this is still an issue? 
otherwise, could we close this issue?

**Comment by gsaslis** [comment]
I will be closing this, after https://github.com/RestComm/Restcomm-Connect/pull/2687 was merged. 

We now have a new quick start guide based on docker compose available under: http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Quick%20Start%20Guide.html

Please feel free to report back if you are still experiencing some issues.
