### ISSUE TITLE
Docker build not working !

### ISSUE THREAD

**Issue by AShabana** [RestComm/Restcomm-Docker#107]
When we run 
`# docker build -t restcomm/restcomm:latest -f Dockerfile .`

the build failed with this error

`Errors were encountered while processing:
 oracle-java7-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

please advice

**Comment by leftyb** [comment]
Ηι @AShabana ,

Τhe problem is that oracle JDK is not longer distributed. Changed last week. 
From now on we will use openjdk. Let me push a fix for it.

Regards

**Comment by leftyb** [comment]
Hi @AShabana,

I just push a fix. Can you please try again. And close issue if works properly.

Thank you.

**Comment by AShabana** [comment]
Thank you , it is built successfully now .
