### ISSUE TITLE
SSL is not configured for Olympus in :latest docker container

### ISSUE THREAD

**Issue by agafox** [RestComm/Restcomm-Docker#110]
**restcomm-olympus.sh** tries to 'patch' sign-in.js controller and it doesn't work for current version of Olympus.
It seems that the right way is to configure **/olympus.war/resources/xml/olympus.xml**

Note: Everything looks OK in Chrome, but it's just use Websocket on port 5082 and doesn't cares...

**Comment by agafox** [comment]
@ammendonca as i understand we can close this issue?

**Comment by ammendonca** [comment]
Yes, fixed with https://github.com/RestComm/Restcomm-Connect/commit/43d54c0dffde2d3339bcef4b7c8c0bb5f6e68d3b and https://github.com/RestComm/Restcomm-Docker/commit/919124473d76945b77c2a09a281d12e6e840e383.
