### ISSUE TITLE
If RESTCOMM_HOST is set, RMS has issues with certificates

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Docker#14]
See https://gist.github.com/deruelle/16d95c8f1c17a1f3ce89, same as issue raised at https://groups.google.com/d/msg/restcomm/wJJC29sLOCc/No9fa8aIEAAJ

**Comment by leftyb** [comment]
The problem was that RESTCOMMHOST was set with an IP. To set the IP must use STATIC_ADDRESS  option.
