### ISSUE TITLE
Can't register to Olympus with Firefox

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Docker#16]
It throws https://gist.github.com/deruelle/28d7ef17251b07f53506

This seems tied to https://github.com/RestComm/Restcomm-Docker/issues/15 where it seems to be using some docker generated random hostname. I think we should use the STATIC_ADDRESS if HOSTNAME or RESTCOMMHOST is not defined for generating the certificate

**Comment by leftyb** [comment]
###Knowing Issue on Firefox###
It is possible that you will not be able to log in to olympus the first time that you will try to connect using Firefox.
To fix this problem please follow the solution provided by [**Faisal Mq**](http://stackoverflow.com/users/379916/faisal-mq) 
on [**http://stackoverflow.com/**](http://stackoverflow.com/questions/11542460/secure-websocket-wss-doesnt-work-on-firefox).
`When you would try to open up wss say using wss://IP:5063, Firefox will keep on giving you error until you open up a separate 
Firefox tab and do try hitting URL [https]://IP:5063 and Confirm Security Exception 
(like you do on Firefox normally for any https based connection). This is really weird and happens only in Firefox.`

**Comment by deruelle** [comment]
Confirmed, let's document this in the README and mark it as Closed

**Comment by deruelle** [comment]
I see it's already documented in https://github.com/RestComm/Restcomm-Docker/commit/3bc210564bb9717ad33ef134b3b5c32cbce97542, so closing

**Comment by leftyb** [comment]
Added to README file:
https://github.com/RestComm/Restcomm-Docker/tree/issue12#knowing-issue-on-firefox

On Fri, Jan 22, 2016 at 1:05 PM, Jean Deruelle notifications@github.com
wrote:

> Confirmed, let's document this in the README and mark it as Closed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RestComm/Restcomm-Docker/issues/16#issuecomment-173880620
> .

## 

## 

Lefteris Banos
Restcomm - DevOps
TeleStax Inc.
Email: eleftherios.banos@telestax.com
