### ISSUE TITLE
Prioritize the ENV variable set from RUN command. 

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Docker#17]
If an environmental variable is set to both ENV_FILE and the RUN command use the one set at the RUN command.

**Comment by deruelle** [comment]
I tried passing secure=false as in command below but I could still connect to https://192.168.0.44/olympus

`docker run --rm -i -t --name=restcomm   -v /var/log/restcomm:/var/log/restcomm/  -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/issue12/scripts/restcomm_env_basicAmazon.sh" -e SECURE="false" -e STATIC_ADDRESS="192.168.0.44"  -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65535:65000-65535/udp mobicents/restcomm:issue12`

**Comment by deruelle** [comment]
I tested the VOICERSS_KEY this was well overriden.
As discussed let's allow SECURESSL=FALSE before closing this issue
