### ISSUE TITLE
Add possibility to use local file for  ENV_CONF_FILE.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Docker#18]
At the moment can only use remote destination to pull END_CONF_FILE. Add functionality for local file as well.

**Comment by leftyb** [comment]
For this issue we can use the option that docker provides :
[docker](https://docs.docker.com/engine/reference/commandline/run/)

`--env-file=[]                 Read in a file of environment variables`

So need to create a file (I created on at the Restcomm-docker repository as a template) 
[file](https://github.com/RestComm/Restcomm-Docker/blob/issue12/scripts/restcomm_localenv_basic)

And the can run the command like :
`docker run  -i -d  --name=restcomm   -v /var/log/restcomm:/var/log/restcomm/ --env-file="/home/ec2-user/restcomm_localenv_basic" -e STATIC_ADDRESS=`curl http://instance-data/latest/meta-data/public-ipv4` -e RESTCOMMHOST="staging.restcomm.com" -e LOG_LEVEL="INFO" -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65535:65000-65535/udp mobicents/restcomm:issue12`

**Comment by deruelle** [comment]
I tried the local file provided but it fails to start with https://gist.github.com/deruelle/f73dd437f7c87ff1bbb6 when doing this docker run command:
`docker run -i --name=restcomm -v /var/restcomm/:/var/restcomm/ -v /var/log/restcomm:/var/log/restcomm/ --env-file="/home/jean/temp/restcomm_localenv_basic" -e STATIC_ADDRESS="192.168.0.44" -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65535:65000-65535/udp mobicents/restcomm:issue12`

**Comment by deruelle** [comment]
Retested. works great without the double quotes
