### ISSUE TITLE
Add Logs for media server on host.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Docker#2]
Need to add logs of mediaserver on host /var/log/restcomm.
Same as with restcomm logs at var/log/restcomm directory of the host.

**Comment by deruelle** [comment]
the logs of MMS are available at docker exec telscale-restcomm tail -f  /opt/TelScale-Restcomm-JBoss-AS7/mediaserver/log/server.log

**Comment by deruelle** [comment]
the logs of Restcomm are available at /var/log/restcomm/mss-server.log

**Comment by leftyb** [comment]
Yes I meant, "same as restcomm logs at var/log/restcomm directory of the host". Sorry for the misleading comment (edit it).

**Comment by leftyb** [comment]
Done.
