### ISSUE TITLE
LOG_LEVEL docker environment variable doesn't seem to affect Media Server logging

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Docker#23]
I tried using `-e LOG_LEVEL="DEBUG"` when starting the container but MS is not showing DEBUG logs.

Also, I noticed that by default Restcomm logs are DEBUG when using docker. I think we need to change that to have less log output, that might affect performance among other things.

**Comment by leftyb** [comment]
Fixed.
