### ISSUE TITLE
shell scripts refactoring

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Docker#29]
hi everybody,

this project has a lot of shell scripts. i think we  should create rules for scritp's files names 
and content of these scripts make some refactoring 
i see 3 big issue:
### 1. Scripts' content

now some scrips combine different logic. example - _restcomm_toolsconf.sh_ - seems it configure 3 different tools. maybe we should split them to 3 different files. 
### 2. Extra shell subcommands

Also some scripts have extra shell subcommands like
-  `cp file  `echo $RESTCOMM_LOGS`/opt/` - no need to call `echo` for variables. 
- somewhere `sed` is used with `"\$var"` instead of `'$var'`
- etc...
### 3. Scripts overriding

some scripts modify another scripts. 

maybe it's ok if we modify some parts of Restcomm distribution(but it's hack anyway)

the biggest issue is when one scripts patch another scrips from current project.

It means that we don't have correct structure and architecture of installation scripts. 
Example `restcomm_conf.sh` patches `docker_do.sh` why??? why we can't change both scripts for new behavior? 
easy solution - use shared config file. it can be shell script with some constants and method to dump it. we can include it to scripts w/o any problems `. installer.conf` or `source installer.conf`

**Comment by deruelle** [comment]
@leftyb can you review this ? "some scripts modify another scripts from current project and even Restcomm distribution." seems pretty bad, as discussed the Docker image should only modify restcomm.conf, anything else that should be modified should be done directly on the Restcomm-Core repository configuration shell scripts, where is the relevant issue for that ?

**Comment by leftyb** [comment]
The specific issue is highly dependent to Restcomm-connect issue [917](https://github.com/RestComm/Restcomm-Connect/issues/917).

Once RetComm-connect auto-configuration scripts refactoring is done, we will be able to refactor as well RestComm-docker RUN scripts. Issue [62](https://github.com/RestComm/Restcomm-Docker/issues/62)
