### ISSUE TITLE
When using the RestCommDocker, it does not work with the restart of the OS(CentOS6).

### ISSUE THREAD

**Issue by motoki01** [RestComm/Restcomm-Docker#31]
Hello, I'm Motoki.
When using the RestCommDocker, it does not work with the restart of the OS(CentOS6).
Place the log at that time.
[restcomm_core.zip](https://github.com/RestComm/Restcomm-Docker/files/129053/restcomm_core.zip)

**Comment by gvagenas** [comment]
Hi @motoki01 , can you please elaborate on what is the problem?

What do you mean it doesn't work after restart of the OS?

Please provide description of the problem with as many details as you can and step by step instructions so I will try to replicate the problem

**Comment by leftyb** [comment]
Close issue due to inactivity.
Maybe related to issue [63](https://github.com/RestComm/Restcomm-Docker/issues/63)
