### ISSUE TITLE
RestComm loggers are poorly configured

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Docker#45]
I am currently load testing RestComm Docker image, so I tried setting the logger threshold to ERROR by using the flag -e LOG_LEVEL="ERROR".

Then I noticed we still had some INFO traces in the RestComm logs.
Checking the logging configuration I noticed most loggers (including root) were still set to INFO. 

```
<subsystem xmlns="urn:jboss:domain:logging:1.2">
            <console-handler name="CONSOLE">
                <level name="INFO"/>
                <formatter>
                    <pattern-formatter pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n"/>
                </formatter>
            </console-handler>
            <periodic-rotating-file-handler name="FILE" autoflush="true">
                <formatter>
                    <pattern-formatter pattern="%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n"/>
                </formatter>
                <file path="/var/log/restcomm/restcomm_core/restcommCore-server.log"/>
                <suffix value=".yyyy-MM-dd"/>
                <append value="true"/>
            </periodic-rotating-file-handler>
            <logger category="com.arjuna">
                <level name="WARN"/>
            </logger>
            <logger category="org.apache.tomcat.util.modeler">
                <level name="WARN"/>
            </logger>
            <logger category="org.jboss.as.config">
                <level name="INFO"/>
            </logger>
            <logger category="org.mobicents.servlet">
                <level name="ERROR"/>
            </logger>
            <logger category="gov.nist">
                <level name="INFO"/>
            </logger>
            <logger category="sun.rmi">
                <level name="WARN"/>
            </logger>
            <logger category="jacorb">
                <level name="WARN"/>
            </logger>
            <logger category="jacorb.config">
                <level name="ERROR"/>
            </logger>
            <root-logger>
                <level name="INFO"/>
                <handlers>
                    <handler name="CONSOLE"/>
                    <handler name="FILE"/>
                </handlers>
            </root-logger>
        </subsystem>
```

The auto-configuration scripts do a poor job at disabling the loggers, only caring about mobicents loggers as seen [here](https://github.com/RestComm/Restcomm-Docker/blob/master/scripts/restcomm_conf.sh#L241)

One final note: Loggers for Media Server _are_ properly set!

**Comment by hamsterksu** [comment]
hi @hrosa 
i'm going to fix logger:
1. Apply one log level for all loggers.
2. Provide posibility to disable file logger at all. (docker collects "system out" automatically). 
maybe for docker it should be disabled by default

WDYT?

**Comment by leftyb** [comment]
@hamsterksu,

Thank you for contributing on that issue. 

On the second bullet, please make by default INFO level on logs. It is true that docker is collecting "system out" automatically but  it is  preferable to use RestComm and Media server proper log system, for various reasons. E.g.. There are various user cases that needs to disable docker logs in general, or as well is much more comfortable to troubleshoot using proper log files.

Regards.

**Comment by hamsterksu** [comment]
hi @hrosa 

i have made changes and would like to get your feedback

i use `xmlstarlet` tool to patch xml files. but i have found that you use another java tool in restcomm-connect project. do i need to use it too? seems `xmlstarlet` more powerful 

https://github.com/hamsterksu/Restcomm-Docker/commit/851b765696538242e81682e51fb17d920b438e59

**Comment by leftyb** [comment]
Hi @hamsterksu ,

We are in the middle of moving all configuration to RC and restcomm.conf. So actually docker only sets the necessary values to restcomm.conf and then RC configuration scripts take care to configure RC properly. This way RC binary  and Docker  can properly sync to allow for the same functionalities.

**Comment by leftyb** [comment]
Fixed at the RestComm  side  after script refactoring. As well added option to change log level on run-time.
