### ISSUE TITLE
Add possibility to add custom java options like java agent

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Docker#53]
add env variable to provide extra value for `JAVA_OPTS`

I propose to use `$JAVA_OPTS_EXTRA`
It will appended before original `$JAVA_OPTS` in `standalone.conf`

**Result:**

```
JAVA_OPTS="$JAVA_OPTS_EXTRA $JAVA_OPTS"
```

**Comment by leftyb** [comment]
hi @hamsterksu,

Thank you for your contribution.
I see that same JAVA_OPTS_EXTRA are used for RestComm and Media Server. I would say that is 
much better to separate, and use different flag for RestComm and MS. 

Something like: RC_JAVA_EXTRA_OPTS & MS_JAVA_EXTRA_OPTS.
As well have in mind that in RestComm side you can add Jboss specific options, that are not used at MS.

One other thing is, how are you planning to combine this contribution with the issue No [57](https://github.com/RestComm/Restcomm-Docker/issues/57) ?

I mean that using JAVA_OPTS_EXTRA, a user can add JAVA options, but as well if I understood good we need to provide the option to modify  Xms`,`Xmx`,`Xmn`and`XX:MaxPermSize`. 

Apart from that, your modifications are functional, I can see that the extra opts are properly added at RestComm and MediaServer running process.

Thank you.

**Comment by hamsterksu** [comment]
@leftyb. thank you for feedback 

agree with you - need to have 2 variables. i will update PR.
Also we can use it to provide `Xms, Xmx, Xmn and XX:MaxPermSize`
