### ISSUE TITLE
Fix PROD_MODE.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Docker#57]
Need to be more configurable or wider so can be used from less strict/specific scenarios.

**Comment by hamsterksu** [comment]
@leftyb could you describe your vision? 
the main idea was getting instance with are ready for performance test. to get maximum we should disable logs and improve java options. https://github.com/RestComm/Restcomm-Connect/blob/master/load_tests/prepare-restcomm-for-perf.sh 

So i think we can replace this flag with the following improvements
1. improve `$LOG_LEVEL` to apply log level for every package and setup it as root log level - https://github.com/RestComm/Restcomm-Docker/issues/45 
2. calculate available memory and provide suitable values for `Xms`, `Xmx`, `Xmn` and `XX:MaxPermSize` or setup it manually like https://github.com/RestComm/load-balancer-docker/blob/master/files/start_loadbalancer.sh
3. provide flag to setup `-Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycle=100 -XX:CMSIncrementalDutyCycleMin=100 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode`
   sure it can be done manually - https://github.com/RestComm/Restcomm-Docker/issues/53 
   but i would like to have automatic mode 

when you specify requirements i will be glad to implement it

**Comment by leftyb** [comment]
Hi @hamsterksu,

Thank you for your time and contribution.

Well my idea is exactly that, to actually be able to arrange/configure the necessary values in accordance with the available specifications of the host that RestComm is running. 
I believe that we shouldn't totally disable logs on Production Mode due to troubleshooting necessities on errors or failures.  

So for the  improvements you are proposing:

1.) I agree that log configuration needs improvement as proposed at #45. So maybe can be removed from the PROD_MODE flag and configure separately with the necessary modifications for #45.
2.& 3) I think that the best approach could be to actually set those values automatically as you say (like providing values after after taking in consideration the available memory)  but as well to be able to manually configured. Saying that if  PROD_MODE is set to TRUE and not any specific values have been set for the values that are needed, then automatically set the values as you propose. But as well give the option to manually set the necessary values and suppress the automatic configuration.

I think this way we can offer a more wide support for the users.
What do you think?
