### ISSUE TITLE
Support for Load Balancer

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Docker#6]
Hello,

Does the restcomm docker image support integration with load balancer?
If not, what is the effort required to implement this? Is this task already in the RestComm roadmap?

Thanks, 
- H

**Comment by leftyb** [comment]
need to apply PR #30

**Comment by antonmry** [comment]
@hrosa @leftyb could you update the actual status of this issue?

After see http://docs.telestax.com/restcomm-configuring-load-balancer/ , I guess it should be closed, isn't it?

**Comment by leftyb** [comment]
Hi @antonmry,

The specific tutorial that you are referring is outdated, I will open an issue to modify the specific documentation entry.
Please for the latest Load Balancer release refer to  [2.0.0](https://telestax.com/restcomm-load-balancer-2-0-0-final/).
We are in the testing phase to support LB 2.0.0 release. As soon as  everything is verified and  tested we will update and close this issue .

Thank you for your contribution.

**Comment by leftyb** [comment]
The integration for LB on RestComm docker is done and tested.
Please refer to the Docker documentation on the Load Balancer section for the necessary configuration.
http://documentation.telestax.com/connect/configuration/docker/Restcomm%20-%20Docker%20Environment%20Variables.html#docker-environment

**Comment by antonmry** [comment]
Thanks @leftyb , well done :+1:
