### ISSUE TITLE
is not possible to modify Xmx, Xms, Xmn params with RC_JAVA_OPTS_EXTRA 

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Docker#75]
Hi everyone,

`Xmx`, `Xms`, `Xmn` are defined in `standalone.conf` file and can not be changed by `RC_JAVA_OPTS_EXTRA`

if you try to override `JAVA_OPTS` at all restcomm doesn't start.

seems we need find these variables in `RC_JAVA_OPTS_EXTRA` and modify `standalone.conf`

**Comment by leftyb** [comment]
@hamsterksu,
I see, I will provide a fix today on that.
Thank you.

**Comment by leftyb** [comment]
@hamsterksu 
Issue  fixed.

Thank you for reporting.

**Comment by hamsterksu** [comment]
hi @leftyb 
have you removed - `RC_JAVA_OPTS_EXTRA` ?
