### ISSUE TITLE
Add configuration parameters for Media Server

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Docker#9]
Regarding RestComm + XMS integration, we need the docker CLI to expose new configuration parameters:
- MS_COMPATIBILITY (mms or xms)
- MS_ADDRESS

Also, because XMS has to run in a separate instance, we need to be able to configure the paths or uri for audio, cache and recording. We can either expose this via configuration parameters for the user to setup manually, or we can have RestComm working with relative URL but "building" them in a clever way (to avoid extra configuration from users whenever we wish to run MS in a different instance).

Example:

```
<cache-uri>/restcomm/cache</cache-uri> 
```

is usually translated to http://private_ip:8080/restcomm/cache or to https://private_ip:8443/restcomm/cache

But for the Media Server to read cached files, the URL should expose the external IP address instead:

http://public_ip:8080/restcomm/cache

Currently, the user is forced to manually edit the restcomm.xml configuration file and use absolute URL to configure these fields. Which can be problematic in case the public IP address of the instance changes: it will force the user to change all these fields again.

The list of suggested input parameters are:
- PROMPTS_URI
- CACHE_URI
- RECORDINGS_PATH (specific to the media server)
- RECORDINGS_URI
- ERROR_DICTIONARY_URI

Note that, in case RestComm decodes relative URLs in a smart way as suggested above, then only the RECORDINGS_PATH parameter would be necessary.

**Comment by leftyb** [comment]
Done in both RestComm-Connect and RestComm-Docker.
